# Generated by Django 5.0.3 on 2024-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_other_picture'),
        ),
    ]
