# Generated by Django 5.0.3 on 2024-10-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvisit',
            name='ip_address',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
    ]
