# Generated by Django 5.0.3 on 2024-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
