# Generated by Django 5.0.4 on 2024-09-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publisher_alter_veblog_img_alter_veblog_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='veblog',
            name='slug',
            field=models.SlugField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
