# Generated by Django 5.0.3 on 2024-09-09 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_veblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='veblog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=type, null=True),
        ),
    ]
