# Generated by Django 5.0.3 on 2024-09-09 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_veblog_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='veblog',
            new_name='Blog',
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_blogcomment_set', to='blog.blog')),
                ('dislike', models.ManyToManyField(related_name='dislike_blogcomment_set', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='like_blogcomment_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blogcomment_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
