# Generated by Django 5.0.3 on 2024-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_veblog_blog_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='admin_verify',
            field=models.BooleanField(default=False),
        ),
    ]
