# Generated by Django 5.0.3 on 2024-10-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-date']},
        ),
    ]
