# Generated by Django 5.1.1 on 2024-09-08 08:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='body',
            field=ckeditor.fields.RichTextField(blank=type, null=True),
        ),
    ]
